export { default as InputTel } from './input-tel';
export { default as IAlert } from './alert';

export { default as IButton } from './i-button.vue';
export { default as ICheckbox } from './checkbox/i-checkbox.vue';
export { default as ICheckboxGroup } from './checkbox/i-checkbox-group.vue';
export { default as IChip } from './i-chip.vue';
export { default as IDatePicker } from './datepicker/i-date-picker.vue';
export { default as IDateRangePicker } from './datepicker/i-date-range-picker.vue';
export { default as IDialog } from './i-dialog.vue';
export { default as IDropdown } from './dropdown/i-dropdown.vue';
export { default as IFileList } from './i-file-list.vue';
export { default as IInput } from './i-input.vue';
export { default as IInputTel } from './input-tel/i-input-tel.vue';
export { default as IInputSuggestion } from './i-input-suggestion.vue';
export { default as IMultipleInput } from './i-multiple-input.vue'
export { default as IMultipleSelect } from './i-multiple-select.vue'
export { default as IPagination } from './i-pagination.vue';
export { default as IPopover } from './i-popover.vue';
export { default as IProgressBar } from './i-progress-bar.vue';
export { default as IRadio } from './i-radio.vue';
export { default as ISelect } from './i-select.vue';
export { default as IStickyBar } from './i-sticky-bar.vue';
export { default as ITable } from './i-table.vue';
export { default as ITabs } from './tabs/i-tabs.vue';
export { default as ITabPane } from './tabs/i-tab-pane.vue';
export { default as ITextArea } from './i-text-area.vue';
export { default as IUpload } from './i-upload.vue';
