export { default as InputTel } from './input-tel';

export { default as IButton } from './i-button.vue';
export { default as ICheckbox } from './checkbox/i-checkbox.vue';
export { default as ICheckboxGroup } from './checkbox/i-checkbox-group.vue';
export { default as IDialog } from './i-dialog.vue';
export { default as IDropdown } from './dropdown/i-dropdown.vue';
export { default as IFileList } from './i-file-list.vue';
export { default as IInput } from './i-input.vue';
export { default as IInputTel } from './input-tel/i-input-tel.vue';
export { default as IInputSuggestion } from './i-input-suggestion.vue';
export { default as IPagination } from './i-pagination.vue';
export { default as IPopover } from './i-popover.vue';
export { default as IProgressBar } from './i-progress-bar.vue';
export { default as IRadio } from './i-radio.vue';
export { default as ITabs } from './tabs/i-tabs.vue';
export { default as ITabPane } from './tabs/i-tab-pane.vue';
export { default as ITextArea } from './i-text-area.vue';
export { default as IUpload } from './i-upload.vue';
